using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSystem.Models.Formas.INV
{
    public class DP03AMOV
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Numero { get; set; }
        public int Linea { get; set; }
        public string Tipo_t { get; set; }
        public string Presenta { get; set; }
        public decimal Factor { get; set; }
        public DateTime? Fecha_tra { get; set; }
        public string Touch { get; set; }
        public string No_parte { get; set; }
        public string Consumo { get; set; }
        public string Bodega { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Despacho { get; set; }
        public decimal Precio_u { get; set; }
        public decimal Precio_t { get; set; }
        public decimal Costo_u { get; set; }
        public decimal Costo_t { get; set; }
        public decimal Poriva { get; set; }
        public decimal Valiva { get; set; }
        public decimal Pordes { get; set; }
        public decimal Valdes { get; set; }
        public decimal Precio_ne { get; set; }
        public decimal Cant_tou { get; set; }
        public decimal Pvpu_tou { get; set; }
        public decimal Pvpt_tou { get; set; }
        public decimal Cubu_tou { get; set; }
        public decimal Cubt_tou { get; set; }
        public decimal Cubica_u { get; set; }
        public decimal Cubica_t { get; set; }
        public string Servicio { get; set; }
        public int Van { get; set; }
        public decimal Desitem { get; set; }
        public string Tprecio { get; set; }
        public string Serie { get; set; }
        public decimal Desit { get; set; }
        public string Iat { get; set; }
        public Boolean Devol { get; set; }
        public decimal Cant_devol { get; set; }
        public string Nservicio { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Boolean Cambia { get; set; }
        public string Tipnc { get; set; }
        public string No_parteco { get; set; }
        public string Cta_costo { get; set; }
        public string S_impcadu { get; set; }
        public string S_autoriza { get; set; }
        public decimal Valor_fac { get; set; }
        public decimal Factorvta { get; set; }
        public string Desfacvta { get; set; }
        public string Ceco { get; set; }
        public decimal Desit2 { get; set; }
        public decimal Kgbrutos { get; set; }
        public decimal Boxes { get; set; }
        public string No_partea { get; set; }
        public decimal Cajetas { get; set; }
        public string Talla { get; set; }
        public string Clase { get; set; }
        public string Calidad { get; set; }
        public string Congela { get; set; }
        public string Tpeso { get; set; }
        public string PesoMar { get; set; }
        public string PesoEmp { get; set; }
        public string Corte { get; set; }
        public string Empaque { get; set; }
        public string Masterp { get; set; }
        public decimal Total_lib { get; set; }
        public decimal Total_kil { get; set; }
        public decimal Total_caj { get; set; }
        public decimal Logistica { get; set; }
        public decimal Descabezado { get; set; }
        public Boolean Es_sobrante { get; set; }
        public string Lote { get; set; }
        public string No_partec { get; set; }
        public string Desfac { get; set; }
        public decimal Factor2 { get; set; }
        public string Recet { get; set; }
        public decimal CostFactor { get; set; }
        public decimal TotFactor { get; set; }
        public string CodFactor { get; set; }
        public decimal CanFactor { get; set; }
        public decimal Num_descu { get; set; }
        public decimal Desit3 { get; set; }
        public decimal Desit4 { get; set; }
        public decimal Desit5 { get; set; }
        public decimal Desit6 { get; set; }
        public decimal Desit7 { get; set; }
        public decimal Desit8 { get; set; }
        public decimal Desit9 { get; set; }
        public decimal Desit10 { get; set; }
        public string DescripD1 { get; set; }
        public string DescripD2 { get; set; }
        public string DescripD3 { get; set; }
        public string DescripD4 { get; set; }
        public string DescripD5 { get; set; }
        public string DescripD6 { get; set; }
        public string DescripD7 { get; set; }
        public string DescripD8 { get; set; }
        public string DescripD9 { get; set; }
        public string DescripD10 { get; set; }
        public decimal Porcenta_n { get; set; }
        public decimal Flete_loc { get; set; }
        public decimal Gastos_loc { get; set; }
        public decimal Valor_fob { get; set; }
        public decimal Flete_int { get; set; }
        public decimal Seguro { get; set; }
        public decimal Valor_cif { get; set; }
        public decimal Valor_aud { get; set; }
        public decimal Gastos_lod { get; set; }
        public decimal Valtransp { get; set; }
        public decimal Valotros { get; set; }
        public decimal Total_sub { get; set; }
        public decimal Costo_uni2 { get; set; }
        public decimal Costo_list { get; set; }
        public decimal PorICE { get; set; }
        public string PartidaICE { get; set; }
    }
}
