// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSystem.Models;

namespace WebSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContextRoot))]
    [Migration("20190415210804_dpinvcab")]
    partial class dpinvcab
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSystem.Models.Formas.CNT.DP01A110", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Codigo_Aux");

                    b.Property<string>("Detalle");

                    b.Property<string>("Estado");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.ToTable("DP01A110");
                });

            modelBuilder.Entity("WebSystem.Models.Formas.COB.DP05A110", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Abierto")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Antic_ncta")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Autofa")
                        .HasColumnType("char(10)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Canton")
                        .HasColumnType("char(2)");

                    b.Property<string>("Cargo_rep")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Catego")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ciudad_col")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ciudad_respal")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Cl_precio")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<string>("Clasifica")
                        .HasColumnType("char(3)");

                    b.Property<string>("Clicodint")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Cod_uees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("Codmain")
                        .HasColumnType("char(6)");

                    b.Property<string>("Colegio")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comenta")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Conse")
                        .HasColumnType("char(8)");

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("Cuota_1")
                        .HasColumnType("numeric (10, 2)");

                    b.Property<decimal>("Cuota_2")
                        .HasColumnType("numeric (10, 2)");

                    b.Property<decimal>("Diasp")
                        .HasColumnType("numeric(3, 0)");

                    b.Property<string>("Digito_tar")
                        .HasColumnType("char(1)");

                    b.Property<string>("Dire_rep")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Direccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(250)")
                        .HasDefaultValue("");

                    b.Property<string>("Direccion2")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email_rep")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Empcli")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<string>("Empre_rep")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Es_contrib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Es_estatal")
                        .HasColumnType("char(1)");

                    b.Property<int>("Es_parterel")
                        .HasColumnType("int");

                    b.Property<string>("Esparterel")
                        .HasColumnType("char(10)");

                    b.Property<string>("Especiali")
                        .HasColumnType("char(2)");

                    b.Property<string>("Estado")
                        .HasColumnType("char(1)");

                    b.Property<string>("Estado_tar")
                        .HasColumnType("char(1)");

                    b.Property<string>("Estcivil")
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("F_cadufa")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("F_emifa")
                        .HasColumnType("datetime");

                    b.Property<string>("Facultad")
                        .HasColumnType("char(2)");

                    b.Property<string>("Fax")
                        .HasColumnType("char(10)");

                    b.Property<DateTime>("Fec_crea")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fec_mod")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ing")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_nac")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ultc")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ultv")
                        .HasColumnType("datetime");

                    b.Property<string>("Fono1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(10)")
                        .HasDefaultValue("");

                    b.Property<string>("Fono2")
                        .HasColumnType("char(10)");

                    b.Property<string>("Fonos_rep")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Lugarnacre")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Marca")
                        .HasColumnType("char(1)");

                    b.Property<string>("Marca2")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("Nhijos")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<string>("Nombre_rep")
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Nomcli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<string>("Ocupa_rep")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Origen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("L");

                    b.Property<string>("Origening")
                        .HasColumnType("char(1)");

                    b.Property<string>("Paisnom")
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Parentezco")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Parroquia")
                        .HasColumnType("char(7)");

                    b.Property<string>("Patcodint")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Patrocina")
                        .HasColumnType("char(6)");

                    b.Property<string>("Pc_ncta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Planea")
                        .HasColumnType("char(10)");

                    b.Property<decimal>("Pordes")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Prodpara")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Profesion")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Programa")
                        .HasColumnType("char(3)");

                    b.Property<string>("Provin_col")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provincia")
                        .HasColumnType("char(10)");

                    b.Property<string>("Recipromo")
                        .HasColumnType("char(1)");

                    b.Property<string>("Repced")
                        .HasColumnType("char(10)");

                    b.Property<string>("Repfono")
                        .HasColumnType("char(10)");

                    b.Property<string>("Replegal")
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Retiene")
                        .HasColumnType("char(1)");

                    b.Property<string>("Ruc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(13)")
                        .HasDefaultValue("");

                    b.Property<string>("Sector")
                        .HasColumnType("char(3)");

                    b.Property<string>("Seriefa")
                        .HasColumnType("char(6)");

                    b.Property<string>("Sexo")
                        .HasColumnType("char(1)");

                    b.Property<string>("St_civil")
                        .HasColumnType("char(1)");

                    b.Property<string>("T_cobro")
                        .HasColumnType("char(3)");

                    b.Property<string>("Tipo_1")
                        .HasColumnType("char(2)");

                    b.Property<string>("Tipo_2")
                        .HasColumnType("char(2)");

                    b.Property<string>("Tipo_cli")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipo_id")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipocli")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipopre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Tipotrans")
                        .HasColumnType("char(3)");

                    b.Property<string>("Titulo")
                        .HasColumnType("char(2)");

                    b.Property<string>("Tp_cliente")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tpdoc")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tpusoprod")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("User_crea")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_mod")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Usoprod")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor_ultc")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Valor_ultv")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Vendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("");

                    b.Property<string>("Webpage")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Zona")
                        .HasColumnType("char(3)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("Empcli");

                    b.ToTable("DP05A110");
                });

            modelBuilder.Entity("WebSystem.Models.Formas.INV.DP03A110", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acceso")
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Anio")
                        .HasColumnType("char(4)");

                    b.Property<string>("Aplica")
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("C_ultcom")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Calidad")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("Cantini")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("Cantini2")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Chasis")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Claint")
                        .HasColumnType("char(10)");

                    b.Property<string>("Clase")
                        .HasColumnType("char(6)");

                    b.Property<string>("Codbarra")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Codcomp")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Codinter")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Codvent")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .HasColumnType("char(3)");

                    b.Property<string>("Comenta")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Congelacion")
                        .HasColumnType("char(1)");

                    b.Property<string>("Corte")
                        .HasColumnType("char(2)");

                    b.Property<decimal>("Costini")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Costo_alor")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Cubicac")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Cubicau")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Desfactor")
                        .HasColumnType("char(10)");

                    b.Property<string>("Desunidad")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Desunidad2")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Desunidad3")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Desunidad4")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Desunidad5")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Empaque")
                        .HasColumnType("char(1)");

                    b.Property<bool>("Es_precio")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<decimal>("Exmax")
                        .HasColumnType("decimal(12, 3)");

                    b.Property<decimal>("Exmin")
                        .HasColumnType("decimal(12, 3)");

                    b.Property<DateTime>("F_aju")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("F_ultcom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("F_ultven")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Factor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6, 0)")
                        .HasDefaultValue(1m);

                    b.Property<DateTime>("Fecha_crea")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_modi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ve1")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ve2")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Hasta2")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Hasta3")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Hasta4")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Hasta5")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imagen2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Iva_sn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<int>("Kmt")
                        .HasColumnType("int");

                    b.Property<string>("Lasting")
                        .HasColumnType("char(10)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Master")
                        .HasColumnType("decimal(16, 6)");

                    b.Property<string>("Meses")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Modidescri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Modipvp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Motor")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("No_parte")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nombre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("Origen")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("P2")
                        .HasColumnType("char(10)");

                    b.Property<string>("P3")
                        .HasColumnType("char(10)");

                    b.Property<string>("Pc_ncta")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pc_ncta2")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pc_ncta3")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Peso")
                        .HasColumnType("char(2)");

                    b.Property<decimal>("Pesobruto")
                        .HasColumnType("decimal(16, 6)");

                    b.Property<decimal>("Pesocaja")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("Pideser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Porcomia")
                        .HasColumnType("numeric (6, 2)");

                    b.Property<decimal>("Porcomib")
                        .HasColumnType("numeric (6, 2)");

                    b.Property<decimal>("Pordes")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Presentacion")
                        .HasColumnType("char(2)");

                    b.Property<string>("Presentacion2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Proveedor")
                        .HasColumnType("char(6)");

                    b.Property<decimal>("Pvpc1")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpc2")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpc3")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpc4")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpc5")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu1")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu2")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu3")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu4")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu5")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Rcantf1")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcantf2")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcantf3")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcantf4")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcantf5")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti1")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti2")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti3")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti4")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti5")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("Subclase")
                        .HasColumnType("char(6)");

                    b.Property<string>("Subclase2")
                        .HasColumnType("char(6)");

                    b.Property<string>("Talla")
                        .HasColumnType("char(3)");

                    b.Property<string>("TieICE")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tip_peso")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Tipopr")
                        .HasColumnType("char(2)");

                    b.Property<string>("Tp_items")
                        .HasColumnType("char(3)");

                    b.Property<string>("Ubica")
                        .HasColumnType("char(10)");

                    b.Property<string>("Ult_prv")
                        .HasColumnType("char(6)");

                    b.Property<decimal>("Ultcompra")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("V_ultcom")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("V_ultven")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Vstock")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Vstock2")
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("No_parte");

                    b.HasIndex("Nombre");

                    b.ToTable("DP03A110");
                });

            modelBuilder.Entity("WebSystem.Models.Formas.INV.DP03ACOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Actcto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Activa_mod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("");

                    b.Property<bool>("AjuSave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Ajuste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("At_exporta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Bode_linea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("CSaldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("C_lineas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Celectro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Codigo_e")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Codigo_i")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Con_ctavta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Control_it")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Cta_provi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("Ctaxpagar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Devol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Es_exporta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Es_lc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Es_produ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Es_reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Fiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Forma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(8)")
                        .HasDefaultValue("");

                    b.Property<string>("Forma2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(8)")
                        .HasDefaultValue("");

                    b.Property<bool>("Generanc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Ing_valdes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Integra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Inventario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Items")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("C");

                    b.Property<string>("Iva")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Iva_credi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Main")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("");

                    b.Property<decimal>("Num_descu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(2, 0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Num_it")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(2, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Numero")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(8)")
                        .HasDefaultValue("00000000");

                    b.Property<string>("Ocultaiva")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<bool>("Od")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Permitedes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Pidecosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("PrinterPDF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Ptovta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Rma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Rt_manu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Serie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(6)")
                        .HasDefaultValue("");

                    b.Property<string>("Signo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Tipo2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Tiport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_aplica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_credito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_deuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_ent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_op")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_ret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tpintegra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tpnumera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Transp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("V_traspor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Validart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.ToTable("DP03ACOM");
                });

            modelBuilder.Entity("WebSystem.Models.Formas.INV.DPINVCAB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Abono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(16, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Aguaje")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<bool>("Anulada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Ap_comi")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Base_0")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Base_tax")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Base_tc")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Bodega")
                        .HasColumnType("char(3)");

                    b.Property<string>("Bodega_d")
                        .HasColumnType("char(3)");

                    b.Property<string>("CSaldo")
                        .HasColumnType("char(1)");

                    b.Property<string>("Cajero")
                        .HasColumnType("char(3)");

                    b.Property<bool>("Canc_lote")
                        .HasColumnType("bit");

                    b.Property<string>("Cancelapto")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cartonera")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Catego")
                        .HasColumnType("int");

                    b.Property<string>("Ce_activo")
                        .HasColumnType("char(1)");

                    b.Property<string>("Ce_autoriz")
                        .HasColumnType("nvarchar(49)");

                    b.Property<string>("Ce_clave")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ce_deserra")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Ce_estado")
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("Ce_fecaut")
                        .HasColumnType("datetime");

                    b.Property<string>("Codigo_e")
                        .HasColumnType("char(2)");

                    b.Property<string>("Codigo_i")
                        .HasColumnType("char(2)");

                    b.Property<string>("Come_anula")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Comenta")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Comenta1")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Comenta2")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Comenta3")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Comenta_re")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Comprodev")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Conceptox")
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Contabi")
                        .HasColumnType("bit");

                    b.Property<string>("Contenedor")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Contrib")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("CpValor_1")
                        .HasColumnType("numeric(16, 2)");

                    b.Property<decimal>("CpValor_2")
                        .HasColumnType("numeric(16, 2)");

                    b.Property<decimal>("CpValor_3")
                        .HasColumnType("numeric(16, 2)");

                    b.Property<decimal>("CpValor_4")
                        .HasColumnType("numeric(16, 2)");

                    b.Property<string>("Cpcodigo_1")
                        .HasColumnType("char(2)");

                    b.Property<string>("Cpcodigo_2")
                        .HasColumnType("char(2)");

                    b.Property<string>("Cpcodigo_3")
                        .HasColumnType("char(2)");

                    b.Property<string>("Cpcodigo_4")
                        .HasColumnType("char(2)");

                    b.Property<string>("Cpcodpla_1")
                        .HasColumnType("char(3)");

                    b.Property<string>("Cpcodpla_2")
                        .HasColumnType("char(3)");

                    b.Property<string>("Cpcodpla_3")
                        .HasColumnType("char(3)");

                    b.Property<string>("Cpcodpla_4")
                        .HasColumnType("char(3)");

                    b.Property<decimal>("Cpvalpla_1")
                        .HasColumnType("numeric (6, 0)");

                    b.Property<decimal>("Cpvalpla_2")
                        .HasColumnType("numeric (6, 0)");

                    b.Property<decimal>("Cpvalpla_3")
                        .HasColumnType("numeric (6, 0)");

                    b.Property<decimal>("Cpvalpla_4")
                        .HasColumnType("numeric (6, 0)");

                    b.Property<string>("Csf_cedula")
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Csf_direcc")
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Csf_nombre")
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Ctacont")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Cubica_t")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<int>("Cuota")
                        .HasColumnType("int");

                    b.Property<string>("Desc_fac")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Dirdes")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Doc_embar")
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("Embarque")
                        .HasColumnType("datetime");

                    b.Property<int>("EsCotiza")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoFac")
                        .HasColumnType("bit");

                    b.Property<string>("Export")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Fac_pro")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Factura")
                        .HasColumnType("char(8)");

                    b.Property<DateTime>("Fec_emb")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fec_fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fec_ini")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_anu")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_anu2")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_clu")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_flu")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_rec")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_tra")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ve1")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ven")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Flete")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("Flete_int")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Flete_loc")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Gasto_loc")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Gastos_lod")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Grupo")
                        .HasColumnType("char(1)");

                    b.Property<string>("Guia_RucDest")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Guia_nDestina")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Guia_placa")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Guia_remi")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Hora_anu")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Hora_rec")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Import")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Impreso")
                        .HasColumnType("char(1)");

                    b.Property<string>("Integracnt")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Integracos")
                        .HasColumnType("char(10)");

                    b.Property<decimal>("Lbasura")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Librasne")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Liquida")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Llegada")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Lrecibida")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Marcas")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Num_conte")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("Numero_b")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("");

                    b.Property<string>("Numfue")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ocompra")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Od")
                        .HasColumnType("bit");

                    b.Property<string>("Ordcom")
                        .HasColumnType("char(8)");

                    b.Property<string>("Pais")
                        .HasColumnType("char(3)");

                    b.Property<string>("Partida")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<string>("Pesada")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Peso_planta")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Pesobru")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pesone")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Por_comitc")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Porcom")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("Pordes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Poriva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Porpromc")
                        .HasColumnType("numeric (16, 8)");

                    b.Property<int>("Programa")
                        .HasColumnType("int");

                    b.Property<string>("Prov_cli")
                        .HasColumnType("char(6)");

                    b.Property<string>("Pto_embar")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Recibido")
                        .HasColumnType("char(1)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Remite")
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("Rendimiento")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("Rma")
                        .HasColumnType("char(1)");

                    b.Property<string>("Rs_scan")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("S_autoriza")
                        .HasColumnType("nvarchar(49)");

                    b.Property<string>("S_impcadu")
                        .HasColumnType("char(8)");

                    b.Property<decimal>("Seguro")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Sellos")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Semana")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Sobr_basura")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Sobr_remite")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Sobr_rendi")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Sobrante")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("St")
                        .HasColumnType("char(2)");

                    b.Property<string>("Status_flu")
                        .HasColumnType("char(1)");

                    b.Property<string>("SubpartiAn")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tam_conte")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Terminos")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Tipo_segur")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Tipo_t")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipo_trans")
                        .HasColumnType("char(3)");

                    b.Property<decimal>("Total_caj")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Total_des")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(16, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Total_ice")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Total_iva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(16, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Total_kil")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Total_lib")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Total_mov")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Total_ser")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("Total_sub")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Total_trn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(16, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Tp_precio")
                        .HasColumnType("char(1)");

                    b.Property<string>("Trans_ruc")
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Transporta")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Transporte")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Trasladox")
                        .HasColumnType("char(1)");

                    b.Property<string>("User_anu")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("User_rec")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Usercla")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Userfec")
                        .HasColumnType("datetime");

                    b.Property<string>("Userfec_2")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Usertim")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Val_trans")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Valcomitc")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Valor_adu")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Valor_cif")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Valor_fob")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Valor_rt")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Valotros")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Valtransp")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<int>("Van")
                        .HasColumnType("int");

                    b.Property<string>("Vapor")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vendedor")
                        .HasColumnType("char(3)");

                    b.Property<string>("Vta_cli")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Vta_dir")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Vta_fo1")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Vta_fo2")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Vta_ruc")
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Fac_pro");

                    b.HasIndex("Fecha_tra");

                    b.HasIndex("Grupo");

                    b.HasIndex("Integracnt");

                    b.HasIndex("Numero");

                    b.HasIndex("Prov_cli");

                    b.HasIndex("Tipo");

                    b.ToTable("DPINVCAB");
                });

            modelBuilder.Entity("WebSystem.Models.main.AlpTabla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Campo1")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Campo2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("");

                    b.Property<string>("Grupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<int>("Lencod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Master")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nomtag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("");

                    b.Property<bool>("Pideval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Sgrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<decimal>("Valor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Valor2")
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("Master");

                    b.HasIndex("Nomtag");

                    b.ToTable("AlpTabla");
                });

            modelBuilder.Entity("WebSystem.Models.main.Gestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Namebmp");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreCorto");

                    b.HasKey("Id");

                    b.ToTable("WebGestiones");
                });

            modelBuilder.Entity("WebSystem.Models.main.Programa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Describe");

                    b.Property<string>("GesApl");

                    b.Property<string>("Msg");

                    b.Property<string>("Nombre");

                    b.Property<string>("Opciones");

                    b.Property<string>("Orden");

                    b.Property<string>("Tarea");

                    b.HasKey("Id");

                    b.ToTable("WebProgramas");
                });

            modelBuilder.Entity("WebSystem.Models.main.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<string>("UserId");

                    b.Property<string>("UserLog");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("WebUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
