// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSystem.Models;

namespace WebSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContextRoot))]
    [Migration("20190408195843_producto")]
    partial class producto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSystem.Models.Formas.CNT.DP01A110", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Codigo_Aux");

                    b.Property<string>("Detalle");

                    b.Property<string>("Estado");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.ToTable("DP01A110");
                });

            modelBuilder.Entity("WebSystem.Models.Formas.COB.DP05A110", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Abierto")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Antic_ncta")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Autofa")
                        .HasColumnType("char(10)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Canton")
                        .HasColumnType("char(2)");

                    b.Property<string>("Cargo_rep")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Catego")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ciudad_col")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ciudad_respal")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Cl_precio")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<string>("Clasifica")
                        .HasColumnType("char(3)");

                    b.Property<string>("Clicodint")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Cod_uees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("Codmain")
                        .HasColumnType("char(6)");

                    b.Property<string>("Colegio")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comenta")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Conse")
                        .HasColumnType("char(8)");

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("Cuota_1")
                        .HasColumnType("numeric (10, 2)");

                    b.Property<decimal>("Cuota_2")
                        .HasColumnType("numeric (10, 2)");

                    b.Property<decimal>("Diasp")
                        .HasColumnType("numeric(3, 0)");

                    b.Property<string>("Digito_tar")
                        .HasColumnType("char(1)");

                    b.Property<string>("Dire_rep")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Direccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(250)")
                        .HasDefaultValue("");

                    b.Property<string>("Direccion2")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email_rep")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Empcli")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<string>("Empre_rep")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Es_contrib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Es_estatal")
                        .HasColumnType("char(1)");

                    b.Property<int>("Es_parterel")
                        .HasColumnType("int");

                    b.Property<string>("Esparterel")
                        .HasColumnType("char(10)");

                    b.Property<string>("Especiali")
                        .HasColumnType("char(2)");

                    b.Property<string>("Estado")
                        .HasColumnType("char(1)");

                    b.Property<string>("Estado_tar")
                        .HasColumnType("char(1)");

                    b.Property<string>("Estcivil")
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("F_cadufa")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("F_emifa")
                        .HasColumnType("datetime");

                    b.Property<string>("Facultad")
                        .HasColumnType("char(2)");

                    b.Property<string>("Fax")
                        .HasColumnType("char(10)");

                    b.Property<DateTime>("Fec_crea")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fec_mod")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ing")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_nac")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ultc")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ultv")
                        .HasColumnType("datetime");

                    b.Property<string>("Fono1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(10)")
                        .HasDefaultValue("");

                    b.Property<string>("Fono2")
                        .HasColumnType("char(10)");

                    b.Property<string>("Fonos_rep")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Lugarnacre")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Marca")
                        .HasColumnType("char(1)");

                    b.Property<string>("Marca2")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("Nhijos")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<string>("Nombre_rep")
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Nomcli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<string>("Ocupa_rep")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Origen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("L");

                    b.Property<string>("Origening")
                        .HasColumnType("char(1)");

                    b.Property<string>("Paisnom")
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Parentezco")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Parroquia")
                        .HasColumnType("char(7)");

                    b.Property<string>("Patcodint")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Patrocina")
                        .HasColumnType("char(6)");

                    b.Property<string>("Pc_ncta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Planea")
                        .HasColumnType("char(10)");

                    b.Property<decimal>("Pordes")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Prodpara")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Profesion")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Programa")
                        .HasColumnType("char(3)");

                    b.Property<string>("Provin_col")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provincia")
                        .HasColumnType("char(10)");

                    b.Property<string>("Recipromo")
                        .HasColumnType("char(1)");

                    b.Property<string>("Repced")
                        .HasColumnType("char(10)");

                    b.Property<string>("Repfono")
                        .HasColumnType("char(10)");

                    b.Property<string>("Replegal")
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Retiene")
                        .HasColumnType("char(1)");

                    b.Property<string>("Ruc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(13)")
                        .HasDefaultValue("");

                    b.Property<string>("Sector")
                        .HasColumnType("char(3)");

                    b.Property<string>("Seriefa")
                        .HasColumnType("char(6)");

                    b.Property<string>("Sexo")
                        .HasColumnType("char(1)");

                    b.Property<string>("St_civil")
                        .HasColumnType("char(1)");

                    b.Property<string>("T_cobro")
                        .HasColumnType("char(3)");

                    b.Property<string>("Tipo_1")
                        .HasColumnType("char(2)");

                    b.Property<string>("Tipo_2")
                        .HasColumnType("char(2)");

                    b.Property<string>("Tipo_cli")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipo_id")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipocli")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipopre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Tipotrans")
                        .HasColumnType("char(3)");

                    b.Property<string>("Titulo")
                        .HasColumnType("char(2)");

                    b.Property<string>("Tp_cliente")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tpdoc")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tpusoprod")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("User_crea")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_mod")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Usoprod")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor_ultc")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("Valor_ultv")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Vendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("");

                    b.Property<string>("Webpage")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Zona")
                        .HasColumnType("char(3)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("Empcli");

                    b.ToTable("DP05A110");
                });

            modelBuilder.Entity("WebSystem.Models.Formas.INV.DP03A110", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acceso")
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Anio")
                        .HasColumnType("char(4)");

                    b.Property<string>("Aplica")
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("C_ultcom")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Calidad")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("Cantini")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("Cantini2")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Chasis")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Claint")
                        .HasColumnType("char(10)");

                    b.Property<string>("Clase")
                        .HasColumnType("char(6)");

                    b.Property<string>("Codbarra")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Codcomp")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Codinter")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Codvent")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .HasColumnType("char(3)");

                    b.Property<string>("Comenta")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Congelacion")
                        .HasColumnType("char(1)");

                    b.Property<string>("Corte")
                        .HasColumnType("char(2)");

                    b.Property<decimal>("Costini")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Costo_alor")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Cubicac")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Cubicau")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Desfactor")
                        .HasColumnType("char(10)");

                    b.Property<string>("Desunidad")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Desunidad2")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Desunidad3")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Desunidad4")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Desunidad5")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Empaque")
                        .HasColumnType("char(1)");

                    b.Property<bool>("Es_precio")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<decimal>("Exmax")
                        .HasColumnType("decimal(12, 3)");

                    b.Property<decimal>("Exmin")
                        .HasColumnType("decimal(12, 3)");

                    b.Property<DateTime>("F_aju")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("F_ultcom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("F_ultven")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Factor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6, 0)")
                        .HasDefaultValue(1m);

                    b.Property<DateTime>("Fecha_crea")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_modi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ve1")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_ve2")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Hasta2")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Hasta3")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Hasta4")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Hasta5")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imagen2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Iva_sn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<int>("Kmt")
                        .HasColumnType("int");

                    b.Property<string>("Lasting")
                        .HasColumnType("char(10)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Master")
                        .HasColumnType("decimal(16, 6)");

                    b.Property<string>("Meses")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Modidescri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Modipvp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Motor")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("No_parte")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nombre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("Origen")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("P2")
                        .HasColumnType("char(10)");

                    b.Property<string>("P3")
                        .HasColumnType("char(10)");

                    b.Property<string>("Pc_ncta")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pc_ncta2")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pc_ncta3")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Peso")
                        .HasColumnType("char(2)");

                    b.Property<decimal>("Pesobruto")
                        .HasColumnType("decimal(16, 6)");

                    b.Property<decimal>("Pesocaja")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("Pideser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Porcomia")
                        .HasColumnType("numeric (6, 2)");

                    b.Property<decimal>("Porcomib")
                        .HasColumnType("numeric (6, 2)");

                    b.Property<decimal>("Pordes")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Presentacion")
                        .HasColumnType("char(2)");

                    b.Property<string>("Presentacion2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Proveedor")
                        .HasColumnType("char(6)");

                    b.Property<decimal>("Pvpc1")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpc2")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpc3")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpc4")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpc5")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu1")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu2")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu3")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu4")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Pvpu5")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Rcantf1")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcantf2")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcantf3")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcantf4")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcantf5")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti1")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti2")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti3")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti4")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Rcanti5")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("Subclase")
                        .HasColumnType("char(6)");

                    b.Property<string>("Subclase2")
                        .HasColumnType("char(6)");

                    b.Property<string>("Talla")
                        .HasColumnType("char(3)");

                    b.Property<string>("TieICE")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tip_peso")
                        .HasColumnType("char(1)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Tipopr")
                        .HasColumnType("char(2)");

                    b.Property<string>("Tp_items")
                        .HasColumnType("char(3)");

                    b.Property<string>("Ubica")
                        .HasColumnType("char(10)");

                    b.Property<string>("Ult_prv")
                        .HasColumnType("char(6)");

                    b.Property<decimal>("Ultcompra")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("V_ultcom")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("V_ultven")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<string>("Vstock")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Vstock2")
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("No_parte");

                    b.HasIndex("Nombre");

                    b.ToTable("DP03A110");
                });

            modelBuilder.Entity("WebSystem.Models.Formas.INV.DP03ACOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Actcto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Activa_mod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("");

                    b.Property<bool>("AjuSave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Ajuste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("At_exporta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Bode_linea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("CSaldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("C_lineas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Celectro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Codigo_e")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Codigo_i")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Con_ctavta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Control_it")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Cta_provi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("Ctaxpagar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Devol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Es_exporta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Es_lc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Es_produ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Es_reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Fiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Forma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(8)")
                        .HasDefaultValue("");

                    b.Property<string>("Forma2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(8)")
                        .HasDefaultValue("");

                    b.Property<bool>("Generanc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Ing_valdes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Integra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Inventario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Items")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("C");

                    b.Property<string>("Iva")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Iva_credi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Main")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("");

                    b.Property<decimal>("Num_descu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(2, 0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Num_it")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(2, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Numero")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(8)")
                        .HasDefaultValue("00000000");

                    b.Property<string>("Ocultaiva")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<bool>("Od")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Permitedes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Pidecosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("PrinterPDF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Ptovta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Rma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Rt_manu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Serie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(6)")
                        .HasDefaultValue("");

                    b.Property<string>("Signo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Tipo2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<string>("Tiport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_aplica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_credito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_deuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_ent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_op")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tp_ret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tpintegra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("");

                    b.Property<string>("Tpnumera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("");

                    b.Property<bool>("Transp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("V_traspor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Validart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.ToTable("DP03ACOM");
                });

            modelBuilder.Entity("WebSystem.Models.main.Gestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Namebmp");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreCorto");

                    b.HasKey("Id");

                    b.ToTable("WebGestiones");
                });

            modelBuilder.Entity("WebSystem.Models.main.Programa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Describe");

                    b.Property<string>("GesApl");

                    b.Property<string>("Msg");

                    b.Property<string>("Nombre");

                    b.Property<string>("Opciones");

                    b.Property<string>("Orden");

                    b.Property<string>("Tarea");

                    b.HasKey("Id");

                    b.ToTable("WebProgramas");
                });

            modelBuilder.Entity("WebSystem.Models.main.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<string>("UserId");

                    b.Property<string>("UserLog");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("WebUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
